apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: logging-system
spec:
  releaseName: loki
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: logging-system
  interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Default values: https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
  values:
    deploymentMode: SimpleScalable

    loki:
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      ingester:
        chunk_encoding: snappy
      querier:
        max_concurrent: 4

      auth_enabled: false

      storage:
        type: s3
        # bucketNames:
        #   admin: prod-marik-loki
        #   chunks: prod-marik-loki
        #   ruler: prod-marik-loki
        s3:
          s3: "s3://prod-marik-loki"
          # region: us-east-1
          # endpoint: s3.amazonaws.com
    backend:
      replicas: 1
      persistence:
        volumeClaimsEnabled: false
      nodeSelector:
        role: "infra"
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "infra"
          effect: "NoSchedule"
    read:
      replicas: 1
      nodeSelector:
        role: "infra"
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "infra"
          effect: "NoSchedule"
    write:
      replicas: 2
      persistence:
        volumeClaimsEnabled: false
      nodeSelector:
        role: "infra"
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "infra"
          effect: "NoSchedule"

    minio:
      enabled: false

    lokiCanary:
      enabled: true

    chunksCache:
      enabled: false
      nodeSelector:
        role: "infra"
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "infra"
          effect: "NoSchedule"

    resultsCache:
      enabled: false
      nodeSelector:
        role: "infra"
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "infra"
          effect: "NoSchedule"

    singleBinary:
      replicas: 0

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0